server:
  port: 8000
spring:
  profiles:
    active: dev
    include: feign
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: localhost:8848

  config:
    import:
      - nacos:common.properties?order


logging:
  level:
    com.atguigu.order.feign: DEBUG